# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.15"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: N2+ gpio add-on"
  org.opencontainers.image.description: "Attempt to get GPIO access via an add-ons for odroid n2+."
  org.opencontainers.image.source: "https://github.com/0n3man/gpio-alarm-contact-sensor"
  org.opencontainers.image.licenses: "Apache License 2.0"
args:
  TEMPIO_VERSION: "2021.09.0"
